name: flutter_place_picker
description: A Flutter plugin which provides 'Picking Places' using OpenStreet and many others Google Maps widget.
version: 0.0.1
homepage: https://github.com/saytoonz/flutter_place_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.1.10
  geolocator: ^9.0.1
  permission_handler: ^10.0.0
  provider: ^6.0.3
  google_maps_webservice: ^0.0.19
  google_api_headers: ^1.3.0
  tuple: ^2.0.0-nullsafety.0
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  # http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
